apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  groups:
    - system:authenticated
  usages:
    - digital signature
    - key encipherment
    - server auth
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQTI4cCtqYWQrSjNGTi80dEl6bUxNS2F4ZTg5ZXhxM1VpdFFVbHpEZTU1M2lRCkd6bmtkc2VXWkh1bDU4dm1DZ2N4d2FmRHFUQklFTFB5L2txUGVvRVVQUHBudXpHUkZVSkYybGpuQ0NBcnVqWFkKRm5kM3VpcjFpc0M4Q1hhY2h5bjJsdHNWWG0wS2wrZlRsQlRsdXlaRUV0Wm4xYXJ6ZWxBVmtOMlYrYnVONFdOSgpvRVNLeU9ObFowVW9KUGZKa25ZNUo2WmhISUd4YWpYd055UzByVUJpc1c2dWh3RTMrRlJuc0FIT3grSVJBOVAzCndsQUVQZ2ptZDRkaWpFdVNCbGlkZTA1RE5aV1dycFFURTJXdndaVVpKQXhVVklDWWdHcGlRMGFvSFZqMm94M0YKVmxzc0JVa0hqdWRqTXdOZlU5UUR5MllTY3R4cmFHMTNjYkV1cmFhMWtRSURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBTVZvWUlvcnZ2YXVHbEVSRlh3Z3AwYmFQL1hlNTFQaFdyclJjSEZ1Tytic1VTYmFmakJXCmNjQ2hwZ1FmUmhhZDhOcHlvcm9Fblh0bWFiWi96azZhMEREMExnZ040dU1JMkljNzV2bzRRTEx6cS93VzNIR2YKZFlFZ0I4ZXBkUWtYZUJzbG9iMXk3VVk1OFBkcnk5ZDc1WmJqbXZuMERXTmpXendzTWEvd0lTajk1eGNPdEpZZQpiN2VGYXhYKzRWeW1SL1RVaDRERUV4STEzNUpXZUtVYWpFYlVvWmhRTU5BVnk2cU9HN292VzdRaEhTNWdOUkV5CmhkRGNoblNnY1pRU1UzWUVtNWJWOUM3YUJjbXRRR3RMVmhXWmxzZlJJZGxPVUlzUmFOQkFJN0sxc0FvQ2xqU3UKWmpMY01Qd2tIUWIwZ2ZSbGNrNnUvMjlNaVU5bDV6V2s2NVU9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kube-apiserver-client-kubelet