apiVersion: apps/v1

kind: DaemonSet

metadata:
  name: monitoring-daemonset
  labels:
    app: monitoring-daemonsetdd

spec:
  selector:
    matchLabels:
      app: monitoring
  template:
    metadata:
      labels:
        app: monitoring
    spec:
      containers:
        - name: elkstack
          image: elasticsearch
