apiVersion: apps/v1

kind: DaemonSet

metadata:
  name: monitoring-daemonset
  labels:
    app: monitoring-daemonsetdd

spec:
  selector:
    matchLables:
      app: monitoring
  template:
    metadata:
      lables:
        app: monitoring
    containers:
      - name: elkstack
        image: elasticsearch
