apiVersion: app/v1
kind: Deployments
metadata:
  name: jenkinsdockerclient
  labels:
    tag: cicd
spec:
  replicas: 2
  matchLables:
    type: web
  template:
    metadata:
      name: cicdwithcontainer
      labels:
        type: web
    spec:
      containers:
        - image: rakeshdyx/jenkins-with-dockerclient
          name: jenkinsdockerclient
          volumeMounts:
            - mountPath: /var/jenkins_home
              name: jenkinvol
            - mountPath: /var/run/docker.sock
              name: dockersock

      volumes:
        - name: jenkinsvol
          hostPath:
            path: /root/jenkis_home
            type: Directory
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
            type: Directory