apiVersion: apps/v1

kind: Deployment

metadata:
  name: blue

spec:
  replicas: 6

  spec:
    containers:
      - name: blue
        image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: color
                operator: In
                values:
                  - blue





