apiVersion: v1
kind: Pod
metadata:
  name: red
spec:
  containers:
  - command:
    - sh
    - -c
    - echo The app is running! && sleep 3600
    image: busybox:1.28
    name: red-container
  initContainers:
    - image: busybox
      name: init-red
      command:
        - sh
        - -c
        - sleep 20



---
#Mltiple init conatiner
apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    name: blue
  spec:
    containers:
    - command:
      - sh
      - -c
      - echo The app is running! && sleep 3600
      image: busybox:1.28
      name: green-container-1
    initContainers:
    - command:
      - sh
      - -c
      - sleep 5
      image: busybox
      name: init-myservice
    - command:
      - sh
      - -c
      - sleep 20
      image: busybox
      name: init-myservice2



