apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp
  labels:
    tire: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      tire: frontend
  template:
    metadata:
      name: webapp-nginx
      labels:
        tire: frontend
    spec:
      containers:
      - name: nginx-web
        image: nginx