apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    creationTimestamp: "2021-01-27T10:09:41Z"
    managedFields:
    - apiVersion: rbac.authorization.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:rules: {}
      manager: kubectl-edit
      operation: Update
      time: "2021-01-27T10:48:42Z"
    name: developer
    namespace: blue
    resourceVersion: "6799"
    selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/blue/roles/developer
    uid: 9163f8bc-e67e-46eb-8f35-47027cd1a539
  rules:
  - apiGroups:
    - ""
    resourceNames:
    - dark-blue-app
    - blue-app
    resources:
    - pods
    verbs:
    - get
    - watch
    - create
    - delete
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

  ---

  ---
  kind: Role
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    namespace: blue
    name: deploy-role
  rules:
    - apiGroups: [ "apps", "extensions" ]
      resources: [ "deployments" ]
      verbs: [ "create" ]
  ---

  kind: RoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: dev-user-deploy-binding
    namespace: blue
  subjects:
    - kind: User
      name: dev-user
      apiGroup: rbac.authorization.k8s.io
  roleRef:
    kind: Role
    name: deploy-role
    apiGroup: rbac.authorization.k8s.io